### ISSUE TITLE
--enable-cal

### ISSUE THREAD

**Issue by gity-up** [MTecknology/tdc#2]
after enabling the calendar feature & clicking the clock, random text and symbols are rendered. i have tried using different fonts & font sizes. what could be the problem? missing dependencies, video driver, composting, desktop environment... ?

![--enable-cal](https://user-images.githubusercontent.com/9837668/66341645-8f97be80-e8fc-11e9-865b-8bd931075803.png)

any help is greatly appreciated, thanx :)

**Comment by MTecknology** [comment]
This is interesting. This is caused by ``cal -h`` now spitting out usage instead of not highlighting today's date, as was previous behavior, and still the behavior documented in the man page.

**Comment by MTecknology** [comment]
Note: https://github.com/karelzak/util-linux/issues/886

**Comment by MTecknology** [comment]
I'm not satisfied with the fix in 4400cf2. This changes the run-time dependency from ``cal (util-linux)`` to ``ncal (bsdmainutils)``. The latter doesn't seem to be available in rhel repos.

**Comment by MTecknology** [comment]
Here we go- this is where the behavior actually changed:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=90483

Since the behavior of ``cal`` is a bit unpredictable (some highlight, some don't, some offer ``-h``, some don't, etc.), I think the only sane solution here is to rely on ncal. Unfortunately, this means ``tdc --enable-cal`` won't be usable on RHEL-based distros because they don't seem to have ``bsdmainutils`` available.

This is exceptionally annoying. :angry:

**Comment by MTecknology** [comment]
@gity-up Thanks for reporting this bug. I don't personally use the calendar feature, so this isn't a bug I would have ever noticed myself. As previously mentioned, this happened because of a breaking change in the `cal` binary provided by `bsdmainutils`. Since this change means `cal` doesn't support the old `-h` option, I'm left to either do a bit of painful hacking or just simply depend on `ncal` over `cal`. At this point, I prefer the latter.

I modified this to use `ncal` and I added some checks so the calendar displays a simple message when `ncal` is not available.

I also tossed this into a release and also uploaded this package for debian unstable. After this migrates to testing, I'll see about uploading for stable-backports. (granted, this doesn't matter if you're not using debian)

**Comment by gity-up** [comment]
been checking for 3 months, when will tdc get migrated to testing or uploaded to stable-backports?

UPDATE: never you mind, i got tdc to install using the unstable repository. the --enable-cal option works beautifully.

the only option that is not working for the calendar is the --hlcolor option.

i wish:

1. there was a way to set the background color for the clock and calendar
2. you could set the height for the clock
3. you could traverse through years instead of just months on the calendar

thank you for fixing the calendar, sincerely.

**Comment by MTecknology** [comment]
I apologize for the delay. I completely forgot about this.

It's now been uploaded. Thanks for the reminder!
